module.exports = {
    LOTTERY_TYPE_TOKEN:         "TOKEN",
    LOTTERY_TYPE_NFT:           "NFT",
    LOTTERY_TYPE_ALLOWLIST:     "ALLOWLIST",
    LOTTERY_TYPE_NAFFLINGS:     "NAFFLINGS",

    RAFFLE_TYPE_RESERVE:        "RESERVE",
    RAFFLE_TYPE_UNCONDITIONAL:  "UNCONDITIONAL",
    RAFFLE_TYPE_UNLIMITED:      "UNLIMITED",
}